In [1]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("cafe_sales_cleaned_final.csv")
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df.head()

Saving cafe_sales_cleaned_final.csv to cafe_sales_cleaned_final.csv

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-Store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-Store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-Store,2023-06-11

In [2]:
df['Year'] = df['Transaction Date'].dt.year
df['Month'] = df['Transaction Date'].dt.month
df['Day'] = df['Transaction Date'].dt.day
df['Day of Week'] = df['Transaction Date'].dt.day_name()

In [3]:
df['Is Weekend'] = df['Day of Week'].isin(['Saturday', 'Sunday'])

In [6]:
def categorize_spending(amount):
    if amount < 10:
        return 'Low'
    elif amount < 25:
        return 'Medium'
    else:
        return 'High'

df['Spending Category'] = df['Total Spent'].apply(categorize_spending)

In [7]:
df['Effective Unit Price'] = df['Total Spent'] / df['Quantity']

In [8]:
df_encoded = pd.get_dummies(df, columns=['Payment Method', 'Location'], drop_first=True)
df_encoded.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Transaction Date,Year,Month,Day,Day of Week,Is Weekend,Spending Category,Effective Unit Price,Payment Method_Credit Card,Payment Method_Digital Wallet,Location_Takeaway
0,TXN_1961373,Coffee,2.0,2.0,4.0,2023-09-08,2023,9,8,Friday,False,Low,2.0,True,False,True
1,TXN_4977031,Cake,4.0,3.0,12.0,2023-05-16,2023,5,16,Tuesday,False,Medium,3.0,False,False,False
2,TXN_4271903,Cookie,4.0,1.0,4.0,2023-07-19,2023,7,19,Wednesday,False,Low,1.0,True,False,False
3,TXN_7034554,Salad,2.0,5.0,10.0,2023-04-27,2023,4,27,Thursday,False,Medium,5.0,False,True,True
4,TXN_3160411,Coffee,2.0,2.0,4.0,2023-06-11,2023,6,11,Sunday,True,Low,2.0,False,True,False

In [9]:
df.to_csv("cafe_sales_featured.csv", index=False)

from google.colab import files
files.download("cafe_sales_featured.csv")